version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/cloud-project-photo-app
hooks:
  ApplicationStart:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: ec2-user