version: 0.2

phases:
  pre_build:
    commands:
      - echo "Install node.js dependencies"
      - cd frontend
      - npm install

  build:
    commands:
    - echo "Showing current directory"
    - ls -la
    - echo "Navigating to the frontend directory"
    - cd frontend  # This is from the root of your repo
    - echo "Building the frontend"
    - npm run build

  post_build:
    commands:
      - echo "Post-build steps"
      # Additional post-build commands like cleanup or tests

artifacts:
  files:
    - '**/*'
  base-directory: 'frontend/build' # replace with the directory where your build outputs its files

cache:
  paths:
    - 'frontend/node_modules/**/*'