version: 0.2

phases:
  pre_build:
    commands:
      - echo "Install node.js dependencies"
      - cd frontend
      - npm install

  build:
    commands:
    - echo "Showing current directory"
    - ls -la
    - echo "Building the frontend"
    - npm run build

  post_build:
    commands:
      - echo "Post-build steps"
      # Additional post-build commands like cleanup or tests

artifacts:
  files:
    - frontend/build/**/*
    - appspec.yml
    - scripts/**/*
  discard-paths: no
  
cache:
  paths:
    - 'frontend/node_modules/**/*'